name: Bug report
description: Report something broken
title: "[Bug] <short title>"
labels: ["todo"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Describe the issue
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      placeholder: 1) ... 2) ... 3) ...
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS / browser / app version
